version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: "enode-dev-mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - 'mongodb_data:/data'
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
           - entity_net
    entity:
        image: anapsix/alpine-java
        container_name: "enode-dev-entity"
        hostname: "entity.localhost"
        ports:
          - 81:8080
        environment:
          - MONGODB_DB_HOST=mongodb
          - MONGODB_DB_PORT=27017
          - MONGODB_DB_NAME=entitiesapp
          - MONGODB_DB_USERNAME=
          - MONGODB_DB_PASSWORD=
        volumes:
        - ./:/app
        entrypoint:
          - java
          - -jar
          - /app/target/entityAPI-1.0-SNAPSHOT.jar
          - " &"
        depends_on:
          - mongodb
        networks:
           - entity_net
volumes:
    mongodb_data:
      driver: local

networks:
    entity_net:
        driver: "bridge"
